services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:v2.0.5
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    environment:
      - SERVER_NAME=EnYouled Server
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - GAME_PORT=15636
      - QUERY_PORT=15637
      - SERVER_SLOTS=16
      - SERVER_IP=0.0.0.0
    volumes:
      - ./enshrouded:/home/steam/enshrouded/savegame